name: flutter_todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  intl: ^0.18.1
  json_theme: ^6.4.0
  mockito: ^5.4.4
  primer_progress_bar: ^0.4.1
  riverpod_annotation: ^2.3.5
  talker_flutter: ^4.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # Add assets to your application
  assets:
    - assets/images/
    - assets/base_theme.json
    - assets/base_dark_theme.json
flutter_intl:
  enabled: true
